on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      #- name: Use Node.js 16
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: 16
      #- name: Install dependencies
      #  run: npm install
      #- name: Cache node_modules
      #  uses: actions/cache@v2
      #  with:
      #    path: ~/.npm
      #    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #    restore-keys: |
      #      ${{ runner.os }}-node-
      #- name: Tests
      #  run: npm test
      #  env:
      #    CI: true
      #- name: Build
      #  run: npm run build
      #- name: Store build as artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: ${{ github.sha }}
      #    path: build
  push:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Download artifact
      #  uses: actions/download-artifact@v2
      #  with:
      #    name: ${{ github.sha }}
      #    path: build
      #- name: Show files
      #  run: ls -la
      #- name: Login to github docker registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.DOCKER_PUSH_TOKEN }}
      #- name: Build and push image
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: .
      #    push: true
      #    tags: ghcr.io/pgrimaud/react-demo:${{ secrets.MAJOR_VERSION }}.${{ secrets.MINOR_VERSION }}.${{ secrets.PATCH_VERSION }}

      - name : Read github event
        run: github.event.head_commit.message

      - name: Update minor version
        if: contains(github.event.head_commit.message, '*/feat/*')
        uses: abhishekpaul/actions-set-secret@master
        with:
          name: 'MINOR_VERSION'
          value: $((${{ secrets.MINOR_VERSION }}+1))
          repository: pgrimaud/react-demo
          token: ${{ secrets.DOCKER_PUSH_TOKEN }}

      - name: Update patch version
        if: contains(github.event.head_commit.message, '*/fix/*')
        uses: abhishekpaul/actions-set-secret@master
        with:
          name: 'PATCH_VERSION'
          value: $((${{ secrets.PATCH_VERSION }}+1))
          repository: pgrimaud/react-demo
          token: ${{ secrets.DOCKER_PUSH_TOKEN }}

